### ISSUE TITLE
[Presentation] What should be in the presentation?

### ISSUE THREAD

**Issue by ariadne240** [swsnu/swpp2020-team2#18]
Write your opinions about it.

**Comment by sdm1230** [comment]
1. 지금까지 구현한것 : Details/ Create, Detail, Modal View 구현
2. 지금까지 한것 에서 어려운점 (챌린지) : Modal을 Calendar에서 띄어서 이후에 페이지 이동
3. 서비스의 유니크한 점 : 학생이 원하는 행사를 자유롭게 올릴 수 있고 또 교내학생주최 행사를 모두 한 눈에 볼 수 있다.
4. 앞으로 할 것 : mysql 과 연동해서 db로 표현하기 및 백엔드서버와 연결

**Comment by ariadne240** [comment]
1.
* I wrote the basic bone code such as .gitignore, .travis.yml, README.md (added badges) of the repo. I changed some settings so that the code would be built in Travis CI.
* I integrated my backend code with MySQL, with a new user account (this is reflected in travis.yml). I checked that this built correctly both in my local and Travis CI.
* I thought all structures/relations of the models and wrote models.py (Completed)
* In views.py I wrote code about sign up/sign in. (send link to signed up user, to activate the user account) Checked that Email verification works by unit testing (mocking email with Django mail.outbox) Also some GETs about user (user/signin, user/:user_id...) are implemented
* In views.py I implemented all GET/POST/DELETE of tag, category, language, background, university, department
* In views.py I implemented upload, get, edit, delete event. (some extra work needed)
* Did 90% work of image managing
2. Handling image upload / get
3. can easily upload student-hosted events and see them in a convenient way (filter, sort, bring). also can freely give opinions by bring/like
4
* Implement rest of apis
* connect to frontend

**Comment by ray017** [comment]
1. What I implemented so far
- I wrote the basic bone code such as package.json, eslint.rc, and some basic codes in src/, such as App.js and index.js, etc.
- And then, I wrote codes for the main page, sign up page, and account activate the page. (only functional. css, and visual things were done by @sdm1230 )
- Made some decorations for mid presentation.
2. Challenging things in the project
It is very difficult that the execution environment is different for each local. That's why we use travis, but travis is almost jammed. And even when travis worked, I really had a hard time running the backend server. To set mysql some environment, I had to format wsl environment I used.

3. Unique characteristic of our service
At least, as far as I know, there is no web service that students can participate in to upload and advertise events in the university. These events were mainly spread through Kakaotalk or Facebook, but they are very closed.

4. What should I do from now
Keep implementing... Also, it will be great if we can come up with a decent ML feature.
