### ISSUE TITLE
Sprint 3 Report

### ISSUE THREAD

**Issue by ray017** [swsnu/swpp2020-team2#32]
Please comment on what to write in sprint 3 report at your side.
Comments will be integrated into sprint 3 report and will be submitted to TAs.

consider below:

**Sprint Progress Report**
Write a short (1~2 pages) summary for sprint and submit it along with the revised documents.

What were the main difficulties so far? You should consider both technical and organization issues.
Were there any features you did not implement as planned, and why? Are you pushing some features to later sprints, and if so, why?
What tests did you prepare for this sprint, and what are they covering? Did the tests you wrote deviate from your plan? What features are you not testing yet? Did you use any test frameworks?
You must include in your progress report a test coverage report. The coverage metric must be over 80%. If it's below 80%, you will lose 10% of the overall score of that sprint. This number may change each sprint. You must specify what tool did you use, and you must include one or more screenshots showing:
The overall coverage metric
The list of classes with lowest coverage. Explain why is the coverage low, and what (if anything) you plan to do about it
Contribution of team members
Tag a branch or revision in your repository to identify the code you want to submit for sprintN (replace N with 1, 2, ...). The date and time of this revision should be before the deadline. This branch should include a README file with instructions on how to run the application and tests.

**Comment by ray017** [comment]
What I have done in sprint 3
- implemented frontend main, sign up, activate pages. (functional things. csses were done by @sdm1230.)
- helped @taekop with a local integration setting.
- tried to help @sdm1230 with a local integration setting, but failed :(
- made a part of the presentation ppt. participated in the presentation.

Difficulties in sprint 3
- backend server didn't work in my local environment.
- css is too hard for me!

How to run frontend
run: from root repository, type following commands.
cd frontend
yarn install
yarn start

test: from root repository, type following commands.
cd frontend
yarn install
yarn test --coverage --watchAll=false

**Comment by ariadne240** [comment]
Consider this:

**Sprint Progress Report**
Write a short (1~2 pages) summary for sprint and submit it along with the revised documents.

What were the main difficulties so far? You should consider both technical and organization issues.
Were there any features you did not implement as planned, and why? Are you pushing some features to later sprints, and if so, why?
What tests did you prepare for this sprint, and what are they covering? Did the tests you wrote deviate from your plan? What features are you not testing yet? Did you use any test frameworks?
You must include in your progress report a test coverage report. The coverage metric must be over 80%. If it's below 80%, you will lose 10% of the overall score of that sprint. This number may change each sprint. You must specify what tool did you use, and you must include one or more screenshots showing:
The overall coverage metric
The list of classes with lowest coverage. Explain why is the coverage low, and what (if anything) you plan to do about it
Contribution of team members
Tag a branch or revision in your repository to identify the code you want to submit for sprintN (replace N with 1, 2, ...). The date and time of this revision should be before the deadline. This branch should include a README file with instructions on how to run the application and tests.

**Comment by ariadne240** [comment]
Features implemented
* I wrote the basic bone code such as .gitignore, .travis.yml, README.md (added badges) of the repo. I changed some settings so that the code would be built in Travis CI.
* Everything done about Backend!
* I integrated my backend code with MySQL, with a new user account (this is reflected in travis.yml). I checked that this built correctly both in my local and Travis CI.
* I thought all structures/relations of the models and wrote models.py (Completed)
* In views.py I wrote code about sign up/sign in. (send link to signed up user, to activate the user account) Checked that Email verification works by unit testing (mocking email with Django mail.outbox) and by real integration test (shown in Mid presentation). Also some GETs about user (user/signin, user/:user_id...) are implemented
* In views.py I implemented all GET/POST/DELETE of tag, category, language, background, university, department
* In views.py I implemented upload, get, edit, delete event/group. (some extra work needed)
* Did 95% work of image managing, but not entirely tested. Not integrated yet.

Test
* coverage (manage.py test) in local env 91 % (88 % in coveralls because of the frontend test issue)

Main Difficulty
* Handling image upload / get (it will be issue again in deployment stage)

Plan
* Implement rest of apis
* connect to frontend

**Comment by ariadne240** [comment]
![Screenshot from 2020-11-14 00-29-58](https://user-images.githubusercontent.com/43671066/99089481-b7357c00-2610-11eb-80b7-17d7f8e68ed8.png)

**Comment by ariadne240** [comment]
The list of classes with lowest coverage. Explain why is the coverage low, and what (if anything) you plan to do about it
views.py has the most functions in the code and thus, in the procedure of fast implementation of functions, it was hard to write test code for all those functions. But it shows already 80 % coverage and I did not face critical problems writing the test codes. So it would be naturally resolved preparing sprint 4. No special treatment would be needed.

**Comment by ariadne240** [comment]
* Were there any features you did not implement as planned, and why?

Some models were changed. For instance, User model divided into User and UserPreference, Background and Language model now has 'name' CharField etd.

Some APIs were also changed. Some missing APIs were added and all apis would now have /api in front of it. /api/university/:name became /api/university/name/:name etc.

* Are you pushing some features to later sprints, and if so, why?
I dunno

**Comment by ariadne240** [comment]
* What tests did you prepare for this sprint, and what are they covering? Did the tests you wrote deviate from your plan? What features are you not testing yet? Did you use any test frameworks?

models.py gave 100 % coverage, and views.py 80 %. Some lately implemented functions, about event and group, in views.py are not tested yet. It was due to limited time to prepare mid presentation, and it will soon be covered. No test failed yet and no tests were giving the answer I did not expect. The code was tested by Django unit test, in the same way with what was learned in the class.

**Comment by taekop** [comment]
What I have done in Sprint 3

1. implement public calendar including sidebar, calendar view, top bar
2. implement one redux action (GET_ALL_EVENTS)
3. modify design of date modal window
4. integrate public calendar, date modal window, and createEvent page

What tests I prepare and cover

public, sidebar, calender - Check view, filter, sort option working properly, Check clicking createEventButton redirect to createEvent page, Check clicking a date showing modal window.
(Calendar.js, SideBar.js, Public.js in picture)
lowest score - Calendar.js 96.61 % Stmts, 86.67 % Funcs, Public.js 95.24 % Funcs - reason unknown


![image](https://user-images.githubusercontent.com/38203748/99101448-fc14df00-261f-11eb-839f-4bbd795cb18e.png)

**Comment by sdm1230** [comment]
What I have done in Sprint 3

- implement & Design EventListModal , EventBox in components
- implement & Design EventDetail, EventModify, EventCreate in container
- Integrate EventListModal to EventDetail page
- Design SignIn, Signup, Activate Page

What tests I prepare and cover

on EventDetail, EventCreate, EventListModal 
- Check view
- Check clicking back button redirect to back page
- Check clicking title button on EventListModal to EventDetail page corresponding to event's id

Difficulties in sprint 3
- backend server with mysql didn't work in my local environment.
- implement page rendering and transfer values, testing through modal component is unfamiliar with me. It is hard.
- Testing on modal component has many problems. 

testing coverage
<img width="670" alt="스크린샷 2020-11-14 오후 5 40 31" src="https://user-images.githubusercontent.com/47305937/99143416-800eab80-26a0-11eb-8dd9-5a77ff4cf6f9.png">

**Comment by sdm1230** [comment]
![Uploading 스크린샷 2020-11-14 오후 5.39.45.png…]()

**Comment by ariadne240** [comment]
Since Report 3 was submitted I close this issue now.
