### ISSUE TITLE
BackLog on Sprint #4

### ISSUE THREAD

**Issue by sdm1230** [swsnu/swpp2020-team2#50]
consider below:

Sprint Progress Report
Write a short (1~2 pages) summary for sprint and submit it along with the revised documents.

What were the main difficulties so far? You should consider both technical and organization issues.
Were there any features you did not implement as planned, and why? Are you pushing some features to later sprints, and if so, why?
What tests did you prepare for this sprint, and what are they covering? Did the tests you wrote deviate from your plan? What features are you not testing yet? Did you use any test frameworks?
You must include in your progress report a test coverage report. The coverage metric must be over 80%. If it's below 80%, you will lose 10% of the overall score of that sprint. This number may change each sprint. You must specify what tool did you use, and you must include one or more screenshots showing:
The overall coverage metric
The list of classes with lowest coverage. Explain why is the coverage low, and what (if anything) you plan to do about it
Contribution of team members
Tag a branch or revision in your repository to identify the code you want to submit for sprintN (replace N with 1, 2, ...). The date and time of this revision should be before the deadline. This branch should include a README file with instructions on how to run the application and tests.

**Comment by sdm1230** [comment]
- What I implemented 
1. Find the error that there is a bug on signing after signup 

2. connect backend with mysql in local environment

3. code implement
    3.1 Details/create
         - add TopBar
    
    3.2 Details/detail
         - add TopBar
   
    3.3 GroupTab_groupmain, search, searchAll 
         - make View with css
         - add '더보기' to move the page for looking for all groups 
   
    3.4 TopBar Components
         - make page render if the click the tab corresponding to its page &
         - active Tab corresponding to page(only for public and group page) using 'tabNum' props
         - add logo image instead of text

- Difficulty & solve
 Active tab corresponding to page rendering is complex, so I solve the issue by calling the topBar with props 'tabNum' which is corresponding to the page. So When call the topBar, we have to call it with giving the correct props 'tabNum'.


- What should I have implemented as planned, but did not?
 I had to complete implement for detail pages. But because of the final exam issue, so I couldn't implement the following features. I'll do them on Sprint5.
1. data connection & flow using backend api with mysql for detail pages.
2. complete testing coverage for detail pages.
3. complete view with css for detail pages.

**Comment by ray017** [comment]
- Implemented group pages: groupmain, search, searchAll, create, detail.
- Implemented reducer and actions that use APIs for group.
- Made tests for newly implemented codes.
- Deployed codes on aws ec2, but having problem with nginx.

I didn't implement all features in group pages and failed to use Nginx and uWSGI for deployment because of some error... I'll keep trying on the next sprint.
I made tests for all files I coded and got 100% coverage.(group files, actions, and reducer files)

**Comment by taekop** [comment]
What I implemented
- complete sidebar checking sort, filter option changes properly
- make prototype of private calendar cloning public calendar
- connect event detail page and backend event api
- write test codes for three things above

**Comment by ariadne240** [comment]
* More accurate handling of images in API
* Modified pylint settings
* Changed travis yaml to make sonarcloud work well
* Made all implemented APIs and their input/output JSON types in the table in the issue so that frontend develops can use them
* Made a workflow: when frontend developers need additional APIs, they write comments on the issue. Then I implement the code by the requirements in the comments
* Following the workflow, I implemented and changed APIs (e.g. image)
* Optimized databases by modifying functions in `models.py` and lots of code
* Tried to debug the problem when @ray017 deployed the code
* changed README to reflect the changed run methods

Before sprint 5, I will implement more backend APIs if frontend developers requests some.

Coverage:
* 94%

**Comment by ariadne240** [comment]
Submitted Sprint 4 backlog
